---
hub: "reichlab/variant-nowcast-hub"
title: "SARS-CoV-2 Variant Nowcast Hub"
pages:
  - text: "Reports"
    menu:
    - text: "2025-10-29"
      href: "2025-10-29-report.md"
    - text: "2025-10-22"
      href: "2025-10-22-report.md"
    - text: "2025-10-15"
      href: "2025-10-15-report.md"
    - text: "2025-10-08"
      href: "2025-10-08-report.md"
    - text: "2025-10-01"
      href: "2025-10-01-report.md"
    - text: "2025-09-24"
      href: "2025-09-24-report.md"
    - text: "2025-09-17"
      href: "2025-09-17-report.md"
    - text: "2025-09-10"
      href: "2025-09-10-report.md"
    - text: "2025-09-03"
      href: "2025-09-03-report.md"
    - text: "2025-08-27"
      href: "2025-08-27-report.md"
    - text: "2025-08-20"
      href: "2025-08-20-report.md"
    - text: "2025-08-13"
      href: "2025-08-13-report.md"
    - text: "2025-08-06"
      href: "2025-08-06-report.md"
    - text: "2025-07-30"
      href: "2025-07-30-report.md"
    - text: "2025-07-23"
      href: "2025-07-23-report.md"
    - text: "2025-07-16"
      href: "2025-07-16-report.md"
    - text: "2025-07-09"
      href: "2025-07-09-report.md"
    - text: "2025-07-02"
      href: "2025-07-02-report.md"
    - text: "2025-06-25"
      href: "2025-06-25-report.md"
    - text: "2025-06-18"
      href: "2025-06-18-report.md"
    - text: "2025-06-11"
      href: "2025-06-11-report.md"
    - text: "2025-06-04"
      href: "2025-06-04-report.md"
    - text: "2025-05-28"
      href: "2025-05-28-report.md"
    - text: "2025-05-21"
      href: "2025-05-21-report.md"
    - text: "2025-05-14"
      href: "2025-05-14-report.md"
    - text: "2025-05-07"
      href: "2025-05-07-report.md"
    - text: "2025-04-30"
      href: "2025-04-30-report.md"
    - text: "2025-04-23"
      href: "2025-04-23-report.md"
    - text: "2025-04-16"
      href: "2025-04-16-report.md"
    - text: "2025-04-09"
      href: "2025-04-09-report.md"
    - text: "2025-04-02"
      href: "2025-04-02-report.md"
    - text: "2025-03-26"
      href: "2025-03-26-report.md"
    - text: "2025-03-19"
      href: "2025-03-19-report.md"
    - text: "2025-03-12"
      href: "2025-03-12-report.md"
    - text: "2025-03-05"
      href: "2025-03-05-report.md"
    - text: "2025-02-26"
      href: "2025-02-26-report.md"
    - text: "2025-02-19"
      href: "2025-02-19-report.md"
    - text: "2025-02-12"
      href: "2025-02-12-report.md"
    - text: "2025-02-05"
      href: "2025-02-05-report.md"
    - text: "2025-01-29"
      href: "2025-01-29-report.md"
    - text: "2025-01-22"
      href: "2025-01-22-report.md"
    - text: "2025-01-15"
      href: "2025-01-15-report.md"
    - text: "2025-01-08"
      href: "2025-01-08-report.md"
    - text: "2025-01-01"
      href: "2025-01-01-report.md"
    - text: "2024-12-25"
      href: "2024-12-25-report.md"
    - text: "2024-12-18"
      href: "2024-12-18-report.md"
    - text: "2024-12-11"
      href: "2024-12-11-report.md"
    - text: "2024-12-04"
      href: "2024-12-04-report.md"
    - text: "2024-11-27"
      href: "2024-11-27-report.md"
